site_name: rust-plus
site_url: https://wavty.github.io/rust-plus/
site_author: wavty
docs_dir: ./docs
repo_name: wavty/rust-plus
repo_url: https://github.com/wavty/rust-plus/
edit_uri: edit/main/docs/

# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  icon:
    repo: fontawesome/brands/github-alt

markdown_extensions:
  - toc:
      permalink: true
      title: On this page
  - tables # 表格
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - admonition # MkDocs 警告框
  - footnotes # 脚注
  - meta # 自定义文章元数据
  - pymdownx.caret # 下划线
  - pymdownx.mark # 文本高亮
  - pymdownx.tilde # 删除线
  - pymdownx.snippets # 内嵌其他文件，可官网搜索使用方法

nav:
  - 首页: index.md
  - 基础知识:
      - concepts/concepts.md
      - concepts/httpie.md
      - concepts/thumbor.md
      - concepts/sql_query.md
