site_name: rust-plus
docs_dir: ./docs
nav:
  - 首页: index.md
  - 基础知识:
      - concepts/concepts.md
      - concepts/httpie.md
# https://juejin.cn/post/7066641709198737416
theme:
  name: material
  codehilite: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      primary: teal
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - admonition #MkDocs 警告框
  - footnotes #脚注
  - meta #自定义文章元数据
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - codehilite:
      use_pygments: true
      linenums: true

# Repository https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#adding-a-git-repository
repo_name: wavty/rust-plus
repo_url: https://github.com/wavty/rust-plus
